# Absenteeism Prediction : Data Science Project 

# Importing Pandas Library and Data

In [1]:
import pandas as pd

raw_csv_data = pd.read_csv("G:\CoachX\Data Science\Day 6\Absenteeism_data.csv")

In [2]:
# Making a Copy of data 
df = raw_csv_data.copy()
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [3]:
# Dropping ID column as it has no relevance in this case
df = df.drop(['ID'], axis = 1)
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

# To Identify the different reasons for absence

In [4]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [5]:
len(df['Reason for Absence'].unique())


28

In [6]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [7]:
# To create dummy variables for the "Reason for Absence" column 
reason_columns = pd.get_dummies(df['Reason for Absence'])
reason_columns

0   1   2   3   4   5   6   7   8   9   ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 28 columns]

In [8]:
# This new column 'check' will contain the sum of values for each row in the original dummy variables columns.
reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns

0  1  2  3  4  5  6  7  8  9  ...  19  21  22  23  24  25  26  27  28  \
0    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   1   0   0   
1    1  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
3    0  0  0  0  0  0  0  1  0  0  ...   0   0   0   0   0   0   0   0   0   
4    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
695  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
696  0  0  0  0  0  0  1  0  0  0  ...   0   0   0   0   0   0   0   0   0   
697  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
698  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
699  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1   

     check  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
695      1  
696      1  
697      1  
698      1  
699      1  

[700 rows x 29 columns]

In [9]:
# To check weather the sum of reasons is equal to 1 in each row 
reason_columns['check'].sum(axis=0)
reason_columns['check'].unique()

array([1], dtype=int64)

In [10]:
# Dropping the 'check' column
reason_columns = reason_columns.drop(['check'], axis = 1)
reason_columns

0   1   2   3   4   5   6   7   8   9   ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 28 columns]

# Drop the 'Reason for Absence' column and to divide it into categories

In [11]:
df = df.drop(['Reason for Absence'], axis = 1)
df

Date  Transportation Expense  Distance to Work  Age  \
0    07/07/2015                     289                36   33   
1    14/07/2015                     118                13   50   
2    15/07/2015                     179                51   38   
3    16/07/2015                     279                 5   39   
4    23/07/2015                     289                36   33   
..          ...                     ...               ...  ...   
695  23/05/2018                     179                22   40   
696  23/05/2018                     225                26   28   
697  24/05/2018                     330                16   28   
698  24/05/2018                     235                16   32   
699  31/05/2018                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                    239.554               30          1         2     1   
1                    239.554               31          1         1     0   
2                    239.554               31          1         0     0   
3                    239.554               24          1         2     0   
4                    239.554               30          1         2     1   
..                       ...              ...        ...       ...   ...   
695                  237.656               22          2         2     0   
696                  237.656               24          1         1     2   
697                  237.656               25          2         0     0   
698                  237.656               25          3         0     0   
699                  237.656               25          1         1     1   

     Absenteeism Time in Hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
695                          8  
696                          3  
697                          8  
698                          2  
699                          2  

[700 rows x 10 columns]

In [12]:
#Dividing 'Reason for Absence' into 4 categories
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

reason_type_1
reason_type_2
reason_type_3
reason_type_4

0      1
1      0
2      1
3      0
4      1
      ..
695    0
696    0
697    0
698    1
699    1
Length: 700, dtype: uint8

In [13]:
#Concatenate Column Values into 'df'
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)
df

Date  Transportation Expense  Distance to Work  Age  \
0    07/07/2015                     289                36   33   
1    14/07/2015                     118                13   50   
2    15/07/2015                     179                51   38   
3    16/07/2015                     279                 5   39   
4    23/07/2015                     289                36   33   
..          ...                     ...               ...  ...   
695  23/05/2018                     179                22   40   
696  23/05/2018                     225                26   28   
697  24/05/2018                     330                16   28   
698  24/05/2018                     235                16   32   
699  31/05/2018                     291                31   40   

     Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                    239.554               30          1         2     1   
1                    239.554               31          1         1     0   
2                    239.554               31          1         0     0   
3                    239.554               24          1         2     0   
4                    239.554               30          1         2     1   
..                       ...              ...        ...       ...   ...   
695                  237.656               22          2         2     0   
696                  237.656               24          1         1     2   
697                  237.656               25          2         0     0   
698                  237.656               25          3         0     0   
699                  237.656               25          1         1     1   

     Absenteeism Time in Hours  0  1  2  3  
0                            4  0  0  0  1  
1                            0  0  0  0  0  
2                            2  0  0  0  1  
3                            4  1  0  0  0  
4                            2  0  0  0  1  
..                         ... .. .. .. ..  
695                          8  1  0  0  0  
696                          3  1  0  0  0  
697                          8  1  0  0  0  
698                          2  0  0  0  1  
699                          2  0  0  0  1  

[700 rows x 14 columns]

In [14]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [15]:
# Renaming the column names to 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4'
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

df.columns = column_names
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

In [16]:
#Reorder Columns
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

df = df[column_names_reordered]
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

# Converting Date value into pandas date format

In [17]:
df['Date']

0      07/07/2015
1      14/07/2015
2      15/07/2015
3      16/07/2015
4      23/07/2015
          ...    
695    23/05/2018
696    23/05/2018
697    24/05/2018
698    24/05/2018
699    31/05/2018
Name: Date, Length: 700, dtype: object

In [18]:
df['Date'][0]

'07/07/2015'

In [19]:
type(df['Date'][0])

str

In [20]:
df['Date'] = pd.to_datetime(df['Date'], format = '%d/%m/%Y')
df['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
         ...    
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, Length: 700, dtype: datetime64[ns]

In [21]:
type(df['Date'])

pandas.core.series.Series

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Reason_1                   700 non-null    uint8         
 1   Reason_2                   700 non-null    uint8         
 2   Reason_3                   700 non-null    uint8         
 3   Reason_4                   700 non-null    uint8         
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64         
 6   Distance to Work           700 non-null    int64         
 7   Age                        700 non-null    int64         
 8   Daily Work Load Average    700 non-null    float64       
 9   Body Mass Index            700 non-null    int64         
 10  Education                  700 non-null    int64         
 11  Children                   700 non-null    int64         
 12  Pets    

# Extracting Month Values from Date column

In [23]:

list_months=[]
df.shape

(700, 14)

In [24]:
# Adding 'Month Value' as the last column
for i in range(df.shape[0]):
    list_months.append(df['Date'][i].month)
    
list_months

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 

In [25]:
len(list_months)

700

In [26]:
df['Month Value'] = list_months
df.head(20)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0          0         0         0         1 2015-07-07                     289   
1          0         0         0         0 2015-07-14                     118   
2          0         0         0         1 2015-07-15                     179   
3          1         0         0         0 2015-07-16                     279   
4          0         0         0         1 2015-07-23                     289   
5          0         0         0         1 2015-07-10                     179   
6          0         0         0         1 2015-07-17                     361   
7          0         0         0         1 2015-07-24                     260   
8          0         0         1         0 2015-07-06                     155   
9          0         0         0         1 2015-07-13                     235   
10         1         0         0         0 2015-07-20                     260   
11         1         0         0         0 2015-07-14                     260   
12         1         0         0         0 2015-07-15                     260   
13         1         0         0         0 2015-07-15                     179   
14         0         0         0         1 2015-07-15                     179   
15         1         0         0         0 2015-07-17                     246   
16         0         0         0         1 2015-07-17                     179   
17         0         0         1         0 2015-07-27                     179   
18         1         0         0         0 2015-07-30                     189   
19         0         0         0         1 2015-08-05                     248   

    Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                 36   33                  239.554               30   
1                 13   50                  239.554               31   
2                 51   38                  239.554               31   
3                  5   39                  239.554               24   
4                 36   33                  239.554               30   
5                 51   38                  239.554               31   
6                 52   28                  239.554               27   
7                 50   36                  239.554               23   
8                 12   34                  239.554               25   
9                 11   37                  239.554               29   
10                50   36                  239.554               23   
11                50   36                  239.554               23   
12                50   36                  239.554               23   
13                51   38                  239.554               31   
14                51   38                  239.554               31   
15                25   41                  239.554               23   
16                51   38                  239.554               31   
17                51   38                  239.554               31   
18                29   33                  239.554               25   
19                25   47                  205.917               32   

    Education  Children  Pets  Absenteeism Time in Hours  Month Value  
0           1         2     1                          4            7  
1           1         1     0                          0            7  
2           1         0     0                          2            7  
3           1         2     0                          4            7  
4           1         2     1                          2            7  
5           1         0     0                          2            7  
6           1         1     4                          8            7  
7           1         4     0                          4            7  
8           1         2     0                         40            7  
9           3         1     1                          8            7  
10          1     

# Extracting the Weekday

In [27]:

df['Date'][699].weekday()

3

In [28]:
df['Date'][699]

Timestamp('2018-05-31 00:00:00')

In [29]:
def date_to_weekday(date_value):
    return date_value.weekday()

df['Day of the Week'] = df['Date'].apply(date_to_weekday)

df.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [30]:
#Dropping Date column
df = df.drop(['Date'], axis = 1)
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [31]:
df.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the Week'], dtype=object)

# Updating Column Names

In [32]:

column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']

df= df[column_names_upd]
df.head()


Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

# Convert 'Education' column into categorical values

In [33]:

df['Education'].unique()


array([1, 3, 2, 4], dtype=int64)

In [34]:
df['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [35]:
df['Education'] = df['Education'].map({1:0, 2:1, 3:1, 4:1})


In [36]:
df['Education'].unique()

array([0, 1], dtype=int64)

In [37]:
df['Education'].value_counts()
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# After validation we have realised the 'Education', 'Children' & 'Pets' column have negligible impact on Absenteeism so we drop them.

In [38]:

df=df.drop(['Education', 'Children', 'Pets'], axis =1)
df

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Absenteeism Time in Hours  
0                 30                          4  
1                 31                          0  
2                 31                          2  
3                 24                          4  
4                 30                          2  
..               ...                        ...  
695               22                          8  
696               24                          3  
697               25                          8  
698               25                          2  
699               25                          2  

[700 rows x 12 columns]

# Preprocessing is done now Creating Checkpoint

In [39]:

df_preprocessed=df.copy()
df_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Absenteeism Time in Hours  
0                 30                          4  
1                 31                          0  
2                 31                          2  
3                 24                          4  
4                 30                          2  
..               ...                        ...  
695               22                          8  
696               24                          3  
697               25                          8  
698               25                          2  
699               25                          2  

[700 rows x 12 columns]

# Creating a logistic regression to predict absenteeism

# Importing relevant library

In [40]:
import numpy as np

In [41]:
#eyeball the data
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Absenteeism Time in Hours  
0               30                          4  
1               31                          0  
2               31                          2  
3               24                          4  
4               30                          2

# Create Targets

In [42]:
#To Find Median of "Absenteeism Time in Hours"
df_preprocessed["Absenteeism Time in Hours"].median()

3.0

# To create targets for our logistic regression

In [43]:
# Targets have to be in categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us
# alternatively, if we had more data, we could have found other ways to deal with the issue 
# for instance, we could have assigned some arbitrary value as a cut-off line, instead of the median

# note that what line does is to assign 1 to anyone who has been absent 4 hours or more (more than 3 hours)
# that is the equivalent of taking half a day off
targets = np.where(df_preprocessed['Absenteeism Time in Hours'] > df_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [44]:
#eyeball the targets array
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [45]:
# create a Series in the original data frame that will contain the targets for the regression
df_preprocessed['Excessive Absenteeism'] = targets

In [46]:
# check what happened to manually see how the targets were created
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Absenteeism Time in Hours  Excessive Absenteeism  
0               30                          4                      1  
1               31                          0                      0  
2               31                          2                      0  
3               24                          4                      1  
4               30                          2                      0

# Check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array

In [47]:
targets.sum()/targets.shape[0]

0.45571428571428574

# Create a checkpoint by dropping the unnecessary variables
# also drop the variables we 'eliminated' after exploring the weights

In [48]:
df_with_targets = df_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week', 'Daily Work Load Average','Distance to Work'],axis=1)
df_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Excessive Absenteeism  
0                     289   33               30                      1  
1                     118   50               31                      0  
2                     179   38               31                      0  
3                     279   39               24                      1  
4                     289   33               30                      0

# Select Inputs for Checkpoint

In [49]:
df_with_targets.shape

(700, 9)

In [50]:
# Selects all rows and all columns until 9 (excluding)
df_with_targets.iloc[:,:9]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Excessive Absenteeism  
0                       289   33               30                      1  
1                       118   50               31                      0  
2                       179   38               31                      0  
3                       279   39               24                      1  
4                       289   33               30                      0  
..                      ...  ...              ...                    ...  
695                     179   40               22                      1  
696                     225   28               24                      0  
697                     330   28               25                      1  
698                     235   32               25                      0  
699                     291   40               25                      0  

[700 rows x 9 columns]

In [51]:
# Selects all rows and all columns but the last one (basically the same operation)
df_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  
0                       289   33               30  
1                       118   50               31  
2                       179   38               31  
3                       279   39               24  
4                       289   33               30  
..                      ...  ...              ...  
695                     179   40               22  
696                     225   28               24  
697                     330   28               25  
698                     235   32               25  
699                     291   40               25  

[700 rows x 8 columns]

In [52]:
# Create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = df_with_targets.iloc[:,:-1]
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  
0                     289   33               30  
1                     118   50               31  
2                     179   38               31  
3                     279   39               24  
4                     289   33               30

# Standardize the data

In [53]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
Scaler = StandardScaler()
Scaler.fit(unscaled_inputs)



# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
#absenteeism_scaler = StandardScaler()

StandardScaler()

In [54]:
df_stand=Scaler.transform(unscaled_inputs)
df_stand

array([[-0.57735027, -0.09298136, -0.31448545, ...,  1.00584437,
        -0.53606239,  0.76743118],
       [-0.57735027, -0.09298136, -0.31448545, ..., -1.57468098,
         2.13080317,  1.00263338],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.6541427 ,
         0.24830984,  1.00263338],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  1.62456682,
        -1.32043461, -0.40857982],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.19094163,
        -0.69293683, -0.40857982],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.03602595,
         0.56205873, -0.40857982]])

In [55]:
df_stand=pd.DataFrame(df_stand, columns=unscaled_inputs.columns)
df_stand.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0 -0.577350 -0.092981 -0.314485  0.821365     0.182726   
1 -0.577350 -0.092981 -0.314485 -1.217485     0.182726   
2 -0.577350 -0.092981 -0.314485  0.821365     0.182726   
3  1.732051 -0.092981 -0.314485 -1.217485     0.182726   
4 -0.577350 -0.092981 -0.314485  0.821365     0.182726   

   Transportation Expense       Age  Body Mass Index  
0                1.005844 -0.536062         0.767431  
1               -1.574681  2.130803         1.002633  
2               -0.654143  0.248310         1.002633  
3                0.854936  0.405184        -0.643782  
4                1.005844 -0.536062         0.767431

# Train Test Split


In [56]:
from sklearn.model_selection import train_test_split
train_test_split(df_stand, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 84   -0.57735 -0.092981 -0.314485  0.821365     1.324766   
 297  -0.57735 -0.092981 -0.314485  0.821365     1.039256   
 359  -0.57735 -0.092981  3.179797 -1.217485    -1.530333   
 450  -0.57735 -0.092981 -0.314485  0.821365    -0.102784   
 444  -0.57735 -0.092981 -0.314485  0.821365    -0.102784   
 ..        ...       ...       ...       ...          ...   
 395  -0.57735 -0.092981 -0.314485  0.821365    -0.959313   
 292  -0.57735 -0.092981 -0.314485  0.821365     1.039256   
 556  -0.57735 -0.092981 -0.314485  0.821365     1.610276   
 580  -0.57735 -0.092981 -0.314485  0.821365    -1.530333   
 140  -0.57735 -0.092981 -0.314485  0.821365    -1.244823   
 
      Transportation Expense       Age  Body Mass Index  
 84                 1.036026  0.562059        -0.408580  
 297                2.213108 -0.849811        -0.408580  
 359               -1.574681  0.091435         0.297027  
 450               -0.654143  0.24

# Declaring Train & Test variables

In [57]:
x_train, x_test, y_train, y_test = train_test_split (df_stand, targets, train_size=0.8, random_state=42)

In [58]:
print(x_train.shape, y_train.shape) 

(560, 8) (560,)


In [59]:
print(x_test.shape, y_test.shape) 

(140, 8) (140,)


# Logistic Regression

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [61]:
# Create a logistic regression object
# fit our train inputs that is basically the whole training part of the machine learning
reg= LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression()

In [62]:
# assess the train accuracy of the model
reg.score(x_train, y_train)

0.7642857142857142

# Manually check the accuracy

In [63]:
# find the model outputs according to our model
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,

In [64]:
# compare them with the targets
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,

In [65]:
# ACTUALLY compare the two variables
model_outputs == y_train

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True, False,  True,
        True, False, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,

In [66]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

428

In [67]:
# get the total number of instances
model_outputs.shape[0]

560

In [68]:
# calculate the accuracy of the model
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7642857142857142

# Finding the Intercept & Coefficients

In [69]:
# get the intercept (bias) of our model
reg.intercept_

array([-0.18577717])

In [70]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.0026008 ,  0.37196832,  1.45382975,  1.32798481,  0.11448557,
         0.75436452, -0.06899196,  0.18903824]])

In [71]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index'], dtype=object)

In [72]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [73]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0                Reason_1     2.002601
1                Reason_2     0.371968
2                Reason_3     1.453830
3                Reason_4     1.327985
4             Month Value     0.114486
5  Transportation Expense     0.754365
6                     Age    -0.068992
7         Body Mass Index     0.189038

In [74]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0               Intercept    -0.185777
1                Reason_1     2.002601
2                Reason_2     0.371968
3                Reason_3     1.453830
4                Reason_4     1.327985
5             Month Value     0.114486
6  Transportation Expense     0.754365
7                     Age    -0.068992
8         Body Mass Index     0.189038

# Intercepting the Coefficients

In [75]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [76]:
# display the df
summary_table

Feature name  Coefficient  Odds_ratio
0               Intercept    -0.185777    0.830459
1                Reason_1     2.002601    7.408299
2                Reason_2     0.371968    1.450587
3                Reason_3     1.453830    4.279472
4                Reason_4     1.327985    3.773432
5             Month Value     0.114486    1.121296
6  Transportation Expense     0.754365    2.126260
7                     Age    -0.068992    0.933334
8         Body Mass Index     0.189038    1.208087

In [77]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                Reason_1     2.002601    7.408299
3                Reason_3     1.453830    4.279472
4                Reason_4     1.327985    3.773432
6  Transportation Expense     0.754365    2.126260
2                Reason_2     0.371968    1.450587
8         Body Mass Index     0.189038    1.208087
5             Month Value     0.114486    1.121296
7                     Age    -0.068992    0.933334
0               Intercept    -0.185777    0.830459

# Testing the Model

In [78]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.7285714285714285

In [79]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.56665558, 0.43334442],
       [0.80608029, 0.19391971],
       [0.83141708, 0.16858292],
       [0.54727184, 0.45272816],
       [0.48146346, 0.51853654],
       [0.11198632, 0.88801368],
       [0.43053835, 0.56946165],
       [0.42145628, 0.57854372],
       [0.94036531, 0.05963469],
       [0.70676355, 0.29323645],
       [0.83035889, 0.16964111],
       [0.5873457 , 0.4126543 ],
       [0.43061579, 0.56938421],
       [0.2578503 , 0.7421497 ],
       [0.70804898, 0.29195102],
       [0.44250225, 0.55749775],
       [0.97776061, 0.02223939],
       [0.08885888, 0.91114112],
       [0.83491366, 0.16508634],
       [0.49779835, 0.50220165],
       [0.85017411, 0.14982589],
       [0.71349178, 0.28650822],
       [0.63623491, 0.36376509],
       [0.59524476, 0.40475524],
       [0.8584014 , 0.1415986 ],
       [0.12010604, 0.87989396],
       [0.51413795, 0.48586205],
       [0.91859817, 0.08140183],
       [0.73945749, 0.26054251],
       [0.52229861, 0.47770139],
       [0.

In [80]:
predicted_proba.shape

(140, 2)

In [81]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.43334442, 0.19391971, 0.16858292, 0.45272816, 0.51853654,
       0.88801368, 0.56946165, 0.57854372, 0.05963469, 0.29323645,
       0.16964111, 0.4126543 , 0.56938421, 0.7421497 , 0.29195102,
       0.55749775, 0.02223939, 0.91114112, 0.16508634, 0.50220165,
       0.14982589, 0.28650822, 0.36376509, 0.40475524, 0.1415986 ,
       0.87989396, 0.48586205, 0.08140183, 0.26054251, 0.47770139,
       0.11342174, 0.1506658 , 0.50565405, 0.75446054, 0.29875354,
       0.59554003, 0.36376509, 0.13854246, 0.73630471, 0.18124728,
       0.57355892, 0.27987324, 0.5625271 , 0.15627185, 0.23615116,
       0.73717152, 0.82519899, 0.87348731, 0.34877389, 0.16063021,
       0.29323645, 0.35623427, 0.51853654, 0.81186045, 0.1465306 ,
       0.23615116, 0.9499837 , 0.29875354, 0.8768953 , 0.65065983,
       0.87870901, 0.1167504 , 0.47107178, 0.57854372, 0.16964111,
       0.08642587, 0.69183708, 0.01088271, 0.28524039, 0.48793654,
       0.29323645, 0.26054251, 0.77135302, 0.35623427, 0.13383

# Save the Model

In [82]:
# import the relevant module
import pickle

In [83]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [84]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(Scaler, file)